export const API_URL = {
  GENERAL: '/general',
  GLOBAL_SEARCH: '/global-search',
  GOOGLE_REVIEWS: '/public/google-reviews',
  LOGIN: '/login',
  LOGOUT: '/logout',
  CATEGORY_LIST: '/category/list',
  GET_COMPOSE_PRODUCTS: '/product-compose/products',
  FIST_STEP_BY_PRODUCT_ID: '/product-compose/product/{productId}',
  COMPOSE_PRODUCTS_BY_ID: '/product-compose/jobs/{id}',
  CREATE_JOB: '/product-compose/jobs',
  JOB_BY_ID: '/product-compose/jobs/{jobId}',
  CALCULATE_PRICE: '/product-compose/jobs/{jobId}/price',
  ADD_TO_CART: '/product-compose/job/{jobId}',
  SAVE_JOB_PARAMETERS: '/product/save-parameters/{jobId}',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CHANGE_PASSWORD: '/settings/personal/password',
  PERSONAL_INFORMATION: '/owner/registration/personal',
  CATEGORY_BY_ID: '/category/{categoryId}',
  PRODUCT_BY_ID: '/product/{productId}',
  CUSTOMER_INFORMATION: '/owner/registration/customer',
  CREATE_PASSWORD: '/owner/registration/password',
  VERIFY_EMAIL: '/email/verify',
  CONFIRM_EMAIL: '/email-update/confirmation',
  DASHBOARD: '/dashboard',
  CART: '/cart',
  CART_BY_ID: '/cart/{cartId}',
  CART_CREATE_QUOTE: '/cart/{cartId}/create',
  SAVE_AS_QUOTE: '/cart/{cartId}/save-quote',
  CART_CHECKOUT: '/cart/{cartId}/checkout',
  CART_PDF: '/cart/{cartId}/preview-pdf',
  SHIPPING_METHODS: '/cart/shipping-methods',
  SHIPPING_LOCATIONS: '/cart/shipping-locations',
  DELIVERY_DETAILS: '/cart/delivery-details',
  DELIVERY_DETAILS_BY_ID: '/cart/{quoteId}/delivery-details',
  DELIVERY_DETAILS_MEDIA: '/cart/{quoteId}/delivery-details/{mediaId}',
  ARTWORKS: '/cart/{cartId}/artworks',
  ARTWORKS_BY_ID: '/cart/{cartId}/artwork/{artworkId}',
  GET_ARTWORK_BY_ID: '/cart/{cartId}/artwork/{jobId}/get/{artworkId}',
  ARTWORKS_BY_JOB_ID: '/cart/{cartId}/artwork/upload/{jobId}',
  CREATE_EMPTY_ARTWORKS: '/cart/{cartId}/artwork/create/{jobId}',
  ARTWORKS_QUANTITY: '/cart/{cartId}/artwork/{artworkId}/quantity',
  TRIM: '/atomyx/bulk/trimbox',
  SCALE: '/atomyx/bulk/autoscale',
  ROTATE: '/atomyx/bulk/rotate',
  RETRY: '/atomyx/bulk/retry',
  RESET_ALL: '/cart/{cartId}/{jobId}/artworks/reset',
  ARTWORKS_COMPLETE: '/cart/{cartId}/{jobId}/artworks/edit-complete',
  ACCEPT_ALL_PROOFS: '/orders/{orderId}/proofs',
  CHANGE_ARTWORK_STATUS: '/orders/jobs/{jobId}/proofs/{artworkId}/status',
  ADMIN_ACCEPT_ARTWORK: '/admin/orders/jobs/{jobId}/proofs/{artworkId}/accept',
  ADMIN_REJECT_ARTWORK: '/admin/orders/jobs/{jobId}/proofs/{artworkId}/reject',
  UPLOAD_ARTWORK: '/orders/jobs/{jobId}/proofs/{artworkId}/upload',
  CONFIRMATION: '/cart/{cartId}/confirmation',
  CREATE_ORDER_IN_CART: '/cart/{cartId}/create-order',
  PAYMENT_CONFIRM: '/cart/{cartId}/credits/confirm',
  PAYMENT_COMPLETE: '/cart/{cartId}/payment/complete',
  SETTINGS_EMPLOYEE: '/settings/employee',
  SETTINGS_EMPLOYEES: '/settings/employees',
  SETTINGS_PERSONAL: '/settings/personal',
  SETTINGS_COMPANY_DETAILS: '/settings/company-details',
  SETTINGS_DELIVERY: '/settings/delivery',
  SETTINGS_NOTIFICATION: '/settings/notification',
  NOTIFICATIONS: '/notifications',
  NOTIFICATIONS_SEEN: '/notifications/mark-seen',
  NOTIFICATIONS_READ_ONE: '/notifications/mark-read',
  NOTIFICATIONS_READ_ALL: '/notifications/mark-all-read',
  QUOTES: '/quotes',
  QUOTES_BY_ID: '/quotes/{quoteId}',
  QUOTES_FILTER: '/quotes/filter',
  QUOTES_COPY: '/quotes/replicate',
  QUOTE_COPY_BY_ID: '/quotes/{quoteId}/replicate',
  QUOTE_JOB: '/quotes/job/{jobId}',
  QUOTE_JOB_COPY: '/quotes/job/{jobId}/replicate',
  QUOTES_CREATE_ORDER: '/quotes/create-order',
  QUOTES_CREATE_ORDER_BY_ID: '/quotes/{quoteId}/create-order',
  QUOTE_PDF: '/quotes/preview-pdf/{quoteId}',
  QUOTE_REFERENCE: '/quotes/{cartId}/quote-reference',
  INVOICES: '/invoices',
  INVOICES_BY_ID: '/invoices/{invoiceId}',
  INVOICES_FILTER: '/invoices/filter',
  INVOICES_PDF: '/invoices/download-pdf/{invoiceId}',
  ADDRESSES: '/addresses',
  ADDRESS_BY_ID: '/addresses/{addressId}',
  ADDRESSR: '/addressr',
  ADDRESSR_IN_LOCATION: '/addressr/in-location-context',
  ADDRESSR_BY_ID: '/addressr/{id}',
  MY_PRODUCTS: '/saved-products',
  MY_PRODUCTS_FILTER: '/saved-products/filter',
  MY_PRODUCTS_BY_ID: '/saved-products/{id}',
  MY_PRODUCTS_ADD_TO_CART: '/saved-products/{jobId}/add-to-cart',
  ORDERS: '/orders',
  ORDER_BY_ID: '/orders/{orderId}',
  ORDER_FILTER: '/orders/filter',
  ORDER_JOB: '/orders/job/{jobId}',
  ORDER_JOB_COPY: '/orders/job/{jobId}/replicate',
  ORDER_CANCEL: '/orders/cancel/{orderId}',
  ORDERS_STATUS: '/admin/orders/status',
  ORDER_STATUSES: '/admin/orders/statuses',
  ORDER_EXPORT: '/admin/orders/{orderId}/xml',
  ORDER_PDF: '/orders/preview-pdf/{orderId}',
  COMPANY_LOGO_PDF: '/orders/company-logo/{orderId}',
  SUPPORT_DOC_PDF: '/orders/support-document/{orderId}',
  PICKUP_LABEL_PDF: '/orders/pickup-label/{orderId}',
  PRINT_PDF: '/orders/print-labels/{orderId}',

  SAVE_DELIVERY_NUMBER: '/orders/delivery-number',
  CUSTOMERS: '/admin/customers',
  CUSTOMERS_BY_ID: '/admin/customers/{customerId}',
  CUSTOMERS_ADDRESS: '/admin/customers/{customerId}/addresses',
  CUSTOMERS_USER_ADDRESS: '/admin/customers/{customerId}/addresses/{addressId}',
  CUSTOMERS_EMPLOYEES: '/admin/customers/{customerId}/employees',
  CUSTOMERS_EMPLOYEE: '/admin/customers/{customerId}/employee',
  CUSTOMERS_USER_EMPLOYEE: '/admin/customers/{customerId}/employee/{userId}',
  CUSTOMERS_ORDERS: '/admin/customers/{customerId}/orders',
  CUSTOMERS_INVOICES: '/admin/customers/{customerId}/invoices',
  UPDATE_MAPS: '/admin/orders/{orderId}/maps/send/artworks',
  BLOG: '/blog-posts',
  BLOG_POSTS: '/blog-posts/{slug}',
  INQUIRIES_FIELDS: '/inquiries/fields',
  INQUIRIES_FIELDS_BY_TYPE: '/inquiries/{inquiryFormType}',
  JOB_APPLICATION: '/job-application',
};

export class UrlGenerator {
  public static generate(url: string, options: { [key: string]: any }): string {
    let modifiedUrl = url;

    Object.entries(options).map(([key, value]: any[]) => {
      const regexp = new RegExp(`{${key}}`, 'g');
      let stringValue: string;

      try {
        stringValue = value.toString();
      } catch {
        throw new Error(`Cannot stringify value ${value}`);
      }

      modifiedUrl = modifiedUrl.replace(regexp, stringValue);
    });

    return modifiedUrl;
  }
}

export function forAdmin(isAdmin: boolean, url: string): string {
  return isAdmin ? '/admin' + url : url;
}
